### ISSUE TITLE
I have a few things for this really cool module

### ISSUE THREAD

**Issue by jbowensii** [Aedif/TokenVariants#45]
This is a great module and does 85% of what I wanted, it was recommended to me on a Reddit blog post.
That post is here and you may want to read it to understand my use case... 
https://www.reddit.com/r/FoundryVTT/comments/sxe1rc/request_help_to_find_a_token_art_module_or_code/

A couple of issues I ran into... 

(1) I could not keep subdirectories under my monster titles, it would not scan/index them so I just moved all of my tokens into the root directory.  Even with MATCH NAME TO FOLDER checked. 

(2) The S3 bucket is hard to setup, through trial and error this is the correct format (the tip on the setup screen did not work for me) "s3:name_of_my_bucket:root_directory/Portraits/"

The name of the S3 bucket does NOT contain its location or any other data from say a URL, then a colon (required) followed by a directory path (any depth and name should work), **_MOST IMPORTANT end with a "/" at least on LINUX._**

(3) the search filter setup on the project site shows the search terms in [ ] Brackets, it took me a while to understand that they must be part of the names, so I just removed them since I did not name my files with brackets.  You may want to clarify that on your project page. 

(4) to get the art and token replaced in a compendium (to make visual searching an option) I had to import the entire compendium, WAIT, then export it again. For the matches 100% were correct, about 15% did not get automatic choices. **_If you started with bad art, it kept the bad art as a choice which was a problem for me._**

Questions:

(1) how do you add multiple terms to a field on the Search Filter Settings. Say I wanted .png and .webp

(2) I could not switch back and for between filenames and pictures when selecting the alternate token. I right-clicked while in the token graphic choice option but the filename list was blank.

Suggested Features:

(1) option to always override current artwork and token (losing current token artwork), or a script to blow away the current artwork in a directory or compendium would be fantastic.

(2) option to have multiple types of tokens, see my example on REDDIT for TOP DOWN tokens since some games like those, but not others... sometimes for BIG monsters, I like top-down even though my other tokens are not. 

(3) A way to update a compendium directly, so everything looks nice when searching through a compendium and sometimes you need a picture to help you choose.

Thank you for your time... 

Discord: jbowens#0415

**Comment by Aedif** [comment]
Hello,

1 - I just tested it and it appears to work fine for me. I'd need more specifics about your setup to identify any potential issues with the setting. i.e. token name, path and name of the images you think should be picked up, filters, etc.

2 - Yes, that's indeed the correct format: **s3:{bucket-name}:{path}**. In programming curcly brackets are often used to indicate something that is to be replaced the curcly brackets themselves included. But I see how that could cause some confusion. The '**/**' at the end I was not aware as being required and I can adjust for that. However in general S3 buckets is not something I can work on right now as for a long time now I have not had an S3 bucket setup to test on.

3 - I'll clarify that in the docs. That's the example that has been used since that's the pattern that was used by the user that originally reuquested this feature. e.g. Adbert [Token].png, Adbert [Portrait].png

4 - That's not really the intended usecase for this module, but I am working on something right now that should help with compendium mapping.

Qs:

1 - For multiple terms you'd need to use RegEx. 'Include' and 'Exclude' are for simple cases, and RegEx is for anyhing that lies outside of that. For multiple file endings it would be something like so: **.*(\.webp|\.png)**

2 - I can't quite understand what you mean here. Could you perhaps rephrase it or provide some screenshots for context?

Features:

1 - As mentioned above I'm working on a feature that should help with image mapping in compendiums. I'll comment here again once it's released so check it out and respond if you think it's still lacking.

2 - Sorry I again am not quite following. This is something that should already be supported by the module. Assuming the naming convention you use is correct you could have both top down and flat images appear under the same token.

e.g. If your token is named 'Goblin', and you have the following 3 images:

PRT_goblin.png
TDT_goblin.png
TKN_goblin.png

All of these will be found by the module. If you want to filter out portraits from the tokens, what you'd need to do is go to filter setting and set up 'PRT_' in the Portrait Include section, and **.\*(TDT_|TKN_).*** in the Token RegEx section.

You can use sites such as this: https://regex101.com/ to test any regex expressions

3 - Again as per above, it's something I'm working on. Look out for updates!

Regards,
Aedif
