### ISSUE TITLE
Cache on load should not happen for players / perf impact

### ISSUE THREAD

**Issue by dhorkin** [Aedif/TokenVariants#64]
The first 30-60 seconds of having Foundry VTT open up, it's extremely sluggish due to Token Variant Art trying to do caching in the background.

It's one thing for this to happen for DMs... but this should NEVER happen at all for players! Players are extremely unlikely to ever need to use Token Variant Art in any capacity, and the few cases they might, they could just ask the DM to pick art for them.

Honestly, though, this behavior is pretty undesirable for DMs, too. My asset library rarely changes - why does it need to rescan unchanged files and cause sluggish performance every time I load Foundry VTT?

I've taken to simply disabling Token Variant Art when I am not actively using it, but this has its own set of annoyances (namely, having to load without it, turn it on, reload, use it a bit, turn it off, reload)

If nothing else, cache should be a low priority task so that it doesn't cause the UI to become nonresponsive. And yes, I know you can disable the cache, but that's a poor option, as well.

**Comment by Aedif** [comment]
Hi,

That's an extremely long waiting time, akin to what I've heard before from ForgeVTT users. If you're using ForgeVTT I'd recommend to make sure that you're using the '**Forge Asset Library Paths**' setting to expose your Assets Library to the module instead of '**Search Paths**'. It has some specific optimisations for ForgeVTT that should massively boost the caching speed.

Now regarding the players having to cache the images too. This should only happen if you have permissions setup in a way that means they may require access the module's search functionality. Enabling any of these features will cause the module to perform a cache operation for the player with that role on game load:

![image](https://user-images.githubusercontent.com/7693704/171812459-b5514ada-3744-44aa-a18f-eeb69d2e7856.png)

With the setup above your players and trusted players will still have access to the Token HUD button but will not require the image cache as that button will only contain shared and wildcard images.


If you're not a ForgeVTT user and the example permissions setup is not ideal for you, then I may need to look into optimizing the caching in some way. 

Usually scanning even 10k+ images isn't an issue, I know some people have massive libraries but... I'd be curious to know just how many images is the module finding for you? 😄
